### ISSUE TITLE
Userpicker

### ISSUE THREAD

**Issue by kluthe** [UCSolarCarTeam/Project-Management-Humhub-Module#3]
Hi. Great Idea! I tried. I installed in latest HumHub. But there is a problem with the userpicker. It is always empty, when you type a name.
![bildschirmfoto 8](https://cloud.githubusercontent.com/assets/2426461/25305278/8dc167e8-2778-11e7-8c30-addf23819617.jpg)

**Comment by ExtraGravity** [comment]
Hi @kluthe thank you for your interest but this project is no longer under active development, feel free to fork it yourself and make the module usable.
